# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82edaf8c1b91da56dc83219361468b0b0a9c5f8d5b8b3c8397f19c3c0fb05c8cf726360f2905ee95953970ac9e2a6d2ce2109e636ea7db718f90442577d0737e

test:
  secret_key_base: 1a0086bbf53b5afa0a7064427780d83dade8922bcc3f7889935e4ac86e6f91e5d48a237647d2bbbc81271ae02afebfbaa17a9c4535b8a2f33a0fa18d5a25594a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
